### ISSUE TITLE
Caso: Coruripe-AL sem diários no QD há mais de 1 ano

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#100]
## CONTEXTO
Não temos mais dados de Coruripe-AL desde março de 2023 ([pesquisa no QD mostrando a data da última edição](https://queridodiario.ok.org.br/pesquisa?city=2702306&sort_by=descending_date)). 

Os atos que temos provém da coleta da associação de municípios de Alagoas. A ausência de novos atos desse município na associação há mais de um ano dá a entender que se desassociou. 

Não foi possível encontrar um novo site onde seus diários estivessem sendo disponibilizados desde então (março/2023 até atualmente) e, dentro do [site oficial da prefeitura](https://www.coruripe.al.gov.br/), a seção de diários oficiais está quebrada. Isso implica que tem mais de 1 ano de diários oficiais sumidos ou inacessíveis, seja do QD ou da Internet como um todo.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
## CONTEXT
We no longer have data for Coruripe-AL since March 2023 ([QD search showing the date of the last edition](https://queridodiario.ok.org.br/pesquisa?city=2702306&sort_by=descending_date)). 

The acts we have come from the collection of the association of municipalities in Alagoas. The absence of new acts from this municipality in the association for over a year suggests that it has disassociated itself. 

It was not possible to find a new website where his diaries were being made available since then and, within the [city hall's official website](https://www.coruripe.al.gov.br/), the official diaries section is broken. This implies that there are more than 1 year of official diaries missing, whether from QD or the Internet as a whole.

**Comment by trevineju** [comment]
Prefeitura corrigiu o site e migrou os diários.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
City Hall corrected the website and migrated the diaries.
