### ISSUE TITLE
Análise temática #1

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/querido-diario-comunidade#57]
### Descrição

Análise de casos específicos encontrados por conta da [Análise Panorâmica #1](https://queridodiario.ok.org.br/educacao/relatorio/1). Pedidos de LAI serão feitos e a análise será publicada na página do [Querido Diário: Tecnologias na Educação](https://queridodiario.ok.org.br/educacao).

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Description

Analysis of specific cases found due to [Panoramic Analysis #1](https://queridodiario.ok.org.br/educacao/relatorio/1). LAI requests will be made and the analysis will be published on the [Dear Diary: Technologies in Education](https://queridodiario.ok.org.br/educacao) page.

**Comment by ogecece** [comment]
[Análise publicada em 29/06/23](https://queridodiario.ok.org.br/educacao/relatorio/2)

**Comment by ogecece** [comment]
["Conectividade nas redes municipais de ensino": análise temática #1 publicada em 29/06/23](https://queridodiario.ok.org.br/educacao/relatorio/2)

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
["Connectivity in municipal education networks": thematic analysis #1 published on 06/29/23](https://queridodiario.ok.org.br/educacao/relatorio/2)
