### ISSUE TITLE
Bacabal-MA demorando para publicar diários

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#60]
No Querido Diário, um raspador tenta coletar diários duas vezes por dia. Na virada do mês, raspa o mês anterior novamente (por redundância, para ter certeza que não perdeu nada). 

Mesmo com essas rotinas, os raspadores estavam dando muito erro de coleta. Isto foi reportado na issue #okfn-brasil/querido-diario/issues/826. Em resumo: 

- Em fevereiro de 2023, a última edição do diário oficial de Bacabal era dezembro/22. (Meses faltantes: Dezembro/22, Janeiro/23 e Fevereiro/23)
- Em março de 2023, novas edições de dezembro/22 apareceram no site e uma de janeiro/23. (Meses faltantes: Janeiro/23, Fevereiro/23 e Março/23) 

A prefeitura demorar, aparentemente meses, para liberar os diários recentes nos fez acionar um pedido de LAI para entender a situação.

No print, de 20/maio/23, mostra que não havia diários de fevereiro, abril e maio, apenas parte de março. 
![Image](https://user-images.githubusercontent.com/44185775/243830896-55576c66-099f-422d-af1e-3ad143e6fb96.png)

Em um novo print hoje, 06/junho/23, mostra fevereiro e março aparentemente incompletos, maio com certeza incompleto e abril sem diários.

![Image](https://user-images.githubusercontent.com/44185775/243830305-c4058eec-8113-43ea-ae3d-7f04a150d600.png)

**Comment by trevineju** [comment]
### TRÂMITE:
PEDIDO: Publicações do Diário Oficial Eletrônico de Bacabal
PROTOCOLO: 0000682
CÓDIGO DE ACESSO: Não se aplica
CADASTRADO EM: 17/03/2023
PRAZO DE ATENDIMENTO: Não informado. Sem prazo no sistema. Utilizado o prazo de referência da LAI. Aguardar até 05/04/2023

### CONTEÚDO:
Prezada/o,

Sobre as publicações do Diário Oficial do Município de Bacabal, solicitamos as seguintes informações e documentos:

1) Qual é o número da edição atual do Diário Oficial de Bacabal? E qual é o período correspondente às informações nele veiculadas?
2) Se a edição atual do Diário Oficial não for a última disponibilizada no site < https://www.bacabal.ma.gov.br/diario >, desde quando ocorre atraso na disponibilização digital?
3) Qual o motivo para que esteja ocorrendo atraso na publicação do Diário Oficial Eletrônico?
3.1) Qual a previsão de retorno da publicação periódica do Diário Oficial Eletrônico? 
3.2) Se não ocorre atraso, em qual endereço online a publicação do Diário Oficial Eletrônico está ocorrendo? Desde quando?
3.3) Caso o endereço online tenha mudado, solicitamos o endereço da página web em que ocorre a publicação periódica do Diário Oficial Eletrônico de Bacabal e link da última edição online veiculada pelo município.
4) Qual é a periodicidade de publicação do Diário Oficial Eletrônico de Bacabal?

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### PENDING:
REQUEST: Publications of the Official Electronic Gazette of Bacabal
PROTOCOL: 0000682
ACCESS CODE: Not applicable
REGISTERED ON: 03/17/2023
SERVICE PERIOD: Not informed. No deadline in the system. The LAI reference period was used. Wait until 05/04/2023

### CONTENT:
Dear,

Regarding the publications of the Official Gazette of the Municipality of Bacabal, we request the following information and documents:

1) What is the current edition number of the Official Gazette of Bacabal? And what is the period corresponding to the information conveyed therein?
2) If the current edition of the Official Gazette is not the last one available on the website < https://www.bacabal.ma.gov.br/diario >, since when is there a delay in digital availability?
3) What is the reason for the delay in the publication of the Electronic Official Gazette?
3.1) What is the expected return of the periodic publication of the Electronic Official Gazette?
3.2) If there is no delay, at which online address is the publication of the Electronic Official Gazette taking place? Since when?
3.3) If the online address has changed, we request the address of the web page where the periodic publication of the Official Electronic Gazette of Bacabal takes place and a link to the latest online edition published by the municipality.
4) What is the frequency of publication of the Official Electronic Gazette of Bacabal?

**Comment by trevineju** [comment]
### TRÂMITE
DATA: 20/04/2023
STATUS: Pedido de informação não respondido

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### PENDING
DATE: 04/20/2023
STATUS: Request for information not answered

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### PROCEDURE: Appeal to the first instance
SUBMISSION: A request for information announcing the appeal to the first instance was registered
PROTOCOL: 0000700
DATE OF SHIPMENT: 04/20/2023
SERVICE PERIOD: 04/24/2023
SUBJECT: [LAI APPEAL - 1ST INSTITUTION] Protocol No. 0000682 - Publications of the Official Electronic Gazette of Bacabal

### CONTENT:
THIS REQUEST FOR INFORMATION IS A FIRST INSTANCE APPEAL OF PROTOCOL No. 0000682, OF 03/17/2023, PURSUANT TO LAW 12527/2011 AND, AS SUCH, MUST BE COMPLETED WITHIN 5 DAYS.

Dear

We resorted to this First Instance of Appeal, due to the failure to comply with the request for information in Protocol No. 0000682, of 03/17/2023, carried out under the terms of the Access to Information Law (Law No. 12,527/2011) through the Electronic System of the Information to Citizens (e-SIC) < https://www.bacabal.ma.gov.br/esic/ >, from the Municipality of Bacabal (MA).

The said request for information was not answered, with no justification or extension period in the Electronic System of the Citizen Information Service.

Due to the absence of the button to register an appeal or complaint in the system, we reiterate the request through this new request for information.

Regarding the publications of the Official Gazette of the Municipality of Bacabal, we reiterate the request for the following information and documents:

1) What is the current edition number of the Official Gazette of Bacabal? And what is the period corresponding to the information conveyed therein?
2) If the current edition of the Official Gazette is not the last one available on the website < https://www.bacabal.ma.gov.br/diario >, since when is there a delay in digital availability?
3) What is the reason for the delay in the publication of the Electronic Official Gazette?
3.1) What is the expected return of the periodic publication of the Electronic Official Gazette?
3.2) If there is no delay, at which online address is the publication of the Electronic Official Gazette taking place? Since when?
3.3) If the online address has changed, we request the address of the web page where the periodic publication of the Official Electronic Gazette of Bacabal takes place and a link to the latest online edition published by the municipality.
4) What is the frequency of publication of the Official Electronic Gazette of Bacabal?

Yours sincerely,

**Comment by trevineju** [comment]
### EXTRA: RECLAMAÇÃO DE NÃO ATENDIMENTO
ENCAMINHAMENTO: Via email
DATA DE ENVIO: 20/04/2023
PRAZO DE ATENDIMENTO: 24/04/2023
REMETENTE: ***@ok.org.br
DESTINATÁRIO: ouvidoria@bacabal.ma.gov.br
CC: contato@ok.org.br
ASSUNTO: [RECLAMAÇÃO] Protocolos nº 0000700 e nº 0000682 - Publicações do Diário Oficial Eletrônico de Bacabal

### CONTEÚDO:

RECLAMAÇÃO POR OMISSÃO:
REGISTRAMOS A PRESENTE MANIFESTAÇÃO DEVIDO À OMISSÃO DE RESPOSTA AO PEDIDO DE INFORMAÇÃO DO PROTOCOLO Nº 0000682, DE 17/03/2023, EM QUE HOUVE DESCUMPRIMENTO DOS PRAZOS E TR MITES PREVISTOS PELA LEI FEDERAL NO. 12.527/2011 (LEI DE ACESSO À INFORMAÇÃO).

Prezada/o,

Registramos um pedido de informação em 17/03//2023, sob o Protocolo nº 0000682, a respeito das publicações do Diário Oficial Eletrônico de Bacabal. O pedido foi registrado através do Sistema Eletrônico do Serviço de Informação ao Cidadão (e-SIC) < https://www.bacabal.ma.gov.br/esic/ >, do Município de Bacabal (MA), nos termos da Lei de Acesso à Informação (Lei nº 12.527/2011).

De acordo com a Lei Federal no 12.527/2011, o prazo para o atendimento é de 20 dias, com possibilidade de 10 dias de prorrogação – prazo que não é informado pelo sistema. Não houve solicitação de prorrogação do prazo, nem resposta ao pedido ou apresentação de justificativa. 

Após o vencimento, tentamos entrar com um recurso nesse pedido mas não havia a possibilidade no site. Por isso, em 20/04/2023, registramos um novo pedido (Protocolo nº 0000700), identificando-o como um recurso à Primeira Instância referente ao pedido original e informando a impossibilidade de realizá-lo naquele mesmo protocolo.

Poderiam, por gentileza responder a solicitação de informação o mais breve possível, considerando os prazos previstos pela Lei Federal no 12.527/2011, apresentando as devidas justificativas para a ausência de retorno?

Abaixo, replicamos o pedido de informação original, cadastrado no Protocolo nº 0000682:

Prezada/o,

Sobre as publicações do Diário Oficial do Município de Bacabal, solicitamos as seguintes informações e documentos:

1) Qual é o número da edição atual do Diário Oficial de Bacabal? E qual é o período correspondente às informações nele veiculadas?
2) Se a edição atual do Diário Oficial não for a última disponibilizada no site < https://www.bacabal.ma.gov.br/diario >, desde quando ocorre atraso na disponibilização digital?
3) Qual o motivo para que esteja ocorrendo atraso na publicação do Diário Oficial Eletrônico?
3.1) Qual a previsão de retorno da publicação periódica do Diário Oficial Eletrônico? 
3.2) Se não ocorre atraso, em qual endereço online a publicação do Diário Oficial Eletrônico está ocorrendo? Desde quando?
3.3) Caso o endereço online tenha mudado, solicitamos o endereço da página web em que ocorre a publicação periódica do Diário Oficial Eletrônico de Bacabal e link da última edição online veiculada pelo município.
4) Qual é a periodicidade de publicação do Diário Oficial Eletrônico de Bacabal?

Aguardamos resposta.

Atenciosamente,

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### EXTRA: CLAIM FOR NON ATTENDANCE
SUBMISSION: Via email
DATE OF SHIPMENT: 04/20/2023
SERVICE PERIOD: 04/24/2023
SENDER: ***@ok.org.br
RECIPIENT: Ouviria@bacabal.ma.gov.br
CC: contato@ok.org.br
SUBJECT: [CLAIM] Protocols No. 0000700 and No. 0000682 - Publications of the Official Electronic Gazette of Bacabal

### CONTENT:

CLAIM FOR OMISSION:
WE REGISTER THIS MANIFESTATION DUE TO THE OMISSION OF A RESPONSE TO THE REQUEST FOR INFORMATION IN PROTOCOL No. 0000682, OF 03/17/2023, IN WHICH THERE WAS NO COMPLIANCE WITH THE DEADLINES AND PROCEDURES PROVIDED BY FEDERAL LAW NO. 12,527/2011 (ACCESS TO INFORMATION LAW).

Dear,

We registered a request for information on 03/17/2023, under Protocol No. 0000682, regarding the publications of the Official Electronic Gazette of Bacabal. The request was registered through the Electronic System of the Citizen Information Service (e-SIC) < https://www.bacabal.ma.gov.br/esic/ >, of the Municipality of Bacabal (MA), pursuant to Law of Access to Information (Law nº 12.527/2011).

According to Federal Law No. 12,527/2011, the deadline for service is 20 days, with the possibility of a 10-day extension – a deadline that is not informed by the system. There was no request for an extension of the deadline, no response to the request or presentation of justification.

After the expiration, we tried to file an appeal on this request but there was no possibility on the website. Therefore, on 04/20/2023, we registered a new request (Protocol No. 0000700), identifying it as an appeal to the First Instance referring to the original request and informing the impossibility of carrying it out in that same protocol.

Could you please respond to the request for information as soon as possible, considering the deadlines provided for by Federal Law No. 12,527/2011, presenting the proper justifications for the lack of return?

Below, we replicate the original request for information, registered in Protocol No. 0000682:

Dear,

Regarding the publications of the Official Gazette of the Municipality of Bacabal, we request the following information and documents:

1) What is the current edition number of the Official Gazette of Bacabal? And what is the period corresponding to the information conveyed therein?
2) If the current edition of the Official Gazette is not the last available on the website < https://www.bacabal.ma.gov.br/diario >, since when is there a delay in digital availability?
3) What is the reason for the delay in the publication of the Electronic Official Gazette?
3.1) What is the expected return of the periodic publication of the Electronic Official Gazette?
3.2) If there is no delay, at which online address is the publication of the Electronic Official Gazette taking place? Since when?
3.3) If the online address has changed, we request the address of the web page where the periodic publication of the Official Electronic Gazette of Bacabal takes place and a link to the latest online edition published by the municipality.
4) What is the frequency of publication of the Official Electronic Gazette of Bacabal?

We await an answer.

Yours sincerely,

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### PROCEDURE: Appeal to the second instance
SUBMISSION: A request for information announcing the appeal to the second instance was registered
PROTOCOL: 0000700
SHIPMENT DATE: 5/4/2023
SERVICE DEADLINE: 05/08/2023

SUBJECT: [LAI APPEAL - 2nd INSTANCE] Protocol No. 0000682 - Publications of the Official Electronic Gazette of Bacabal

### CONTENT
THIS REQUEST FOR INFORMATION IS A SECOND INSTANCE APPEAL OF PROTOCOL No. 0000682, OF 03/17/2023, PURSUANT TO LAW 12527/2011 AND, AS SUCH, MUST BE COMPLETED WITHIN 5 DAYS.

Dear,

We resorted to this Second Instance of Appeal, due to non-compliance with the request for information in Protocol No. 0000682, of 03/17/2023, carried out under the terms of the Law on Access to Information (Law No. 12,527/2011) through the Electronic System of the Information to Citizens (e-SIC) < https://www.bacabal.ma.gov.br/esic/ >, from the Municipality of Bacabal (MA).

The aforementioned request for information was not answered, without a justification or extension period in the Electronic System of the Citizen Information Service.

After the expiration, we tried to file an appeal on this request but there was no possibility on the website. Therefore, on 04/20/2023, we registered a new request (Protocol No. 0000700), identifying it as an appeal to the First Instance referring to the original request and informing the impossibility of carrying it out in that same protocol.

According to Federal Law 12,527/2011, the deadline for attending the First Instance of Appeal is 5 days. And there was no response to the request or presentation of justification.

And, also on 04/20/2023, we filed a complaint due to failure to respond to said request for information, in which there was non-compliance with the deadlines and procedures provided for by Federal Law 12,527/2011, by sending an email.

Regarding the publications of the Official Gazette of the Municipality of Bacabal, we reiterate the request for information and documents through this new request for information. Below, we replicate the original content, registered in Protocol No. 0000682:

“Dear,

Regarding the publications of the Official Gazette of the Municipality of Bacabal, we request the following information and documents:

1) What is the current edition number of the Official Gazette of Bacabal? And what is the period corresponding to the information conveyed therein?
2) If the current edition of the Official Gazette is not the last available on the website < https://www.bacabal.ma.gov.br/diario >, since when is there a delay in digital availability?
3) What is the reason for the delay in the publication of the Electronic Official Gazette?
3.1) What is the expected return of the periodic publication of the Electronic Official Gazette?
3.2) If there is no delay, at which online address is the publication of the Electronic Official Gazette taking place? Since when?
3.3) If the online address has changed, we request the address of the web page where the periodic publication of the Official Electronic Gazette of Bacabal takes place and a link to the latest online edition published by the municipality.
4) What is the periodicity of publication of the Official Electronic Gazette of Bacabal?"

We await an answer.

Yours sincerely,

**Comment by trevineju** [comment]
### TRÂMITE: Resposta ao recurso em 2ª instância
RECEBIDA EM: 29/05/2023
PRAZO PARA RECURSO: 07/06/2023

### CONTEÚDO
Bom dia! Segue respectivamente as respostas.

1) Ultima edição do dia 08/05/2023 Edição n° BAC20230508. Informações dos dias 05/05 e 08/05.
2) Todas as edições estão disponíveis no site https://www.bacabal.ma.gov.br/diario
3) Não existe atraso. O endereço é o mesmo do item 2.
4) Não existe uma regra quanto a periodicidade, o diário é alimentado de acordo com a demanda de cada setor. Os setores enviam seus atos pra publicação, cada semana existe uma demanda diferente.

Obrigada pelo contato!

ASSESSORIA SECRETARIA DE ADMINISTRAÇÃO

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### PROCESSING: Response to appeal in 2nd instance
RECEIVED ON: 05/29/2023
DEADLINE FOR APPEAL: 06/07/2023

### CONTENT
Good morning! The answers follow respectively.

1) Last issue on 05/08/2023 Issue No. BAC20230508. Information from the 05/05th and 08/05.
2) All editions are available at https://www.bacabal.ma.gov.br/diario
3) There is no delay. The address is the same as in item 2.
4) There is no rule as to periodicity, the journal is fed according to the demand of each sector. The sectors send their acts for publication, each week there is a different demand.

Thanks for the contact!

ADVISORY SECRETARY OF ADMINISTRATION

**Comment by trevineju** [comment]
### Comentários:
Como a resposta demorou 2 meses para chegar (o processo foi começado em 17/03/2023 e obtivemos resposta em 29/05/2023), a publicação de Diários Oficiais de Bacabal-MA avançou no intermédio, ainda que no mesmo ritmo "atrasado" de antes.

Entretanto, o padrão continua: 
- A imagem abaixo, de 20/05/23, mostra que não havia diários de fevereiro, abril e maio e apenas parte de março. 
![Image](https://user-images.githubusercontent.com/44185775/243830896-55576c66-099f-422d-af1e-3ad143e6fb96.png)
- Em 06/06/23, fevereiro e março estão aparentemente incompletos, maio com certeza incompleto e abril sem diários.
![Image](https://user-images.githubusercontent.com/44185775/243830305-c4058eec-8113-43ea-ae3d-7f04a150d600.png)

Assim, pode-se assumir que a resposta recebida foi insatisfatória. 

### STATUS
A OKBR estava enfrentando diversas dificuldades em pedidos de LAI para municípios no contexto do Querido Diário: Tecnologias na Educação, relatada em [matéria no blog](https://ok.org.br/noticia/apos-11-anos-de-lai-governos-locais-ainda-dificultam-pedidos-de-acesso-a-informacao/). Neste contexto, a continuidade deste pedido foi despriorizada (os diários estão sendo publicados, ainda que em uma frequência estranha) e não recorremos novamente.  

O raspador para Bacabal-MA segue desabilitado no projeto.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
### Comments:
As the response took 2 months to arrive (the process was started on 03/17/2023 and we received a response on 05/29/2023), the publication of Diários Oficiais de Bacabal-MA advanced in the middle, although at the same "delayed" pace " from before.

However, the pattern continues:
- The image below, from 05/20/23, shows that there were no diaries for February, April and May and only part of March.
![Image](https://user-images.githubusercontent.com/44185775/243830896-55576c66-099f-422d-af1e-3ad143e6fb96.png)
- As of 06/06/23, February and March are apparently incomplete, May definitely incomplete, and April without journals.
![Image](https://user-images.githubusercontent.com/44185775/243830305-c4058eec-8113-43ea-ae3d-7f04a150d600.png)

Thus, it can be assumed that the response received was unsatisfactory.

### STATUS
OKBR was facing several difficulties in LAI requests for municipalities in the context of Querido Diário: Tecnologias na Educação, reported in [blog article](https://ok.org.br/noticia/apos-11-anos-de- lai-local-governments-still-difficult-requests-for-access-to-information/). In this context, the continuation of this request was not prioritized (the diaries are being published, albeit at a strange frequency) and we have not appealed again.

The scraper for Bacabal-MA is still disabled in the project.
