### ISSUE TITLE
Caso: Sumiço de diários de Peritoró-MA

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario-comunidade#62]
## CONTEXTO
Começamos a receber erros de raspagem para Peritóro-MA. O motivo é que o site publicador de diários mudou. 
Nesses casos, para preservar o histórico de diários, é comum que prefeituras mantenham os dois sites ou migre o conteúdo do site sendo abandonado para o novo. Entretanto, Peritoró-MA não o fez, apenas derrubou o site anterior, cessando o acesso à anos de diários oficiais do município.  

Evidências:
O site que o Querido Diário costumava coletar edições de diários era ([`a2202c5`](https://github.com/okfn-brasil/querido-diario/blob/a2202c5ef5cd5cf232f582d12cbce081b78ebb9a/data_collection/gazette/spiders/ma_peritoro.py)): https://www.peritoro.ma.gov.br/diario/ 
Esta URL redireciona para [outro endereço](https://peritoro.ma.gov.br/diario-oficial-eletronico/) que indica os diários agora estão sendo publicados em: https://dom.peritoro.ma.gov.br/

Neste novo endereço é possível ver (ao acessar a última página) que tem um diário de 2018, um de 2022 e aí passa para março/2023, e a publicação segue desta última data em diante. Onde estão as edições de 2018 até março/2023? 
![Image](https://user-images.githubusercontent.com/44185775/252420956-6e0b00ad-0320-4133-8f88-ff478452ff8a.png)

O [Querido Diário tem as edições de 04-01-2021 até 04-04-2023](https://queridodiario.ok.org.br/pesquisa?city=2108454) (trocar a ordenação para recentes/antigos para conferir o intervalo), coletadas no site anterior antes dele ser suspenso, sendo, aparentemente, o único local público onde estão esses diários. 

## AÇÃO SUGERIDA: Fazer um pedido de LAI para encaminhar a questão
- Quem for atuar nesse caso, sinalize aqui para que outras pessoas não façam atividades já sendo executadas.
- Se a ação for fazer um pedido de LAI, é necessário primeiro verificar se ela é regulamentada no município para confirmar os procedimentos, prazos e instâncias pelas quais o pedido tramitaria. 
- É importante acompanhar os prazos dos processos e trazer as devolutivas. Caso não hajam prazos oficiais, estipular alguma data que pareça adequada para tentar novamente ou para tentar por outra via. 
- Pode usar o espaço da thread para conversar sobre a questão (tomar outra ação que não a inicialmente sugerida na abertura, desenvolver um rascunho inicial de texto, fazer recurso, próximos passos, quem acionar, etc).

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
## CONTEXT
We started getting scraping errors for Peritóro-MA. The reason is that the diary publishing site has changed.
In these cases, to preserve the diary history, it is common for city halls to maintain both sites or migrate the content of the site being abandoned to the new one. However, Peritoró-MA did not do so, it just overthrew the previous site, ceasing access to years of the municipality's official journals.

Evidences:
The site that Querido Diário used to collect diary issues was ([`a2202c5`](https://github.com/okfn-brasil/querido-diario/blob/a2202c5ef5cd5cf232f582d12cbce081b78ebb9a/data_collection/gazette/spiders/ma_peritoro.py)) : https://www.peritoro.ma.gov.br/diario/
This URL redirects to [another address](https://peritoro.ma.gov.br/diario-oficial-eletronico/) which indicates the diaries are now being published at: https://dom.peritoro.ma.gov. br/

In this new address it is possible to see (when accessing the last page) that there is a diary from 2018, one from 2022 and then it goes to March/2023, and the publication continues from this last date onwards. Where are the 2018 editions until March/2023?
![Image](https://user-images.githubusercontent.com/44185775/252420956-6e0b00ad-0320-4133-8f88-ff478452ff8a.png)

[Querido Diário has editions from 04-01-2021 to 04-04-2023](https://queridodiario.ok.org.br/pesquisa?city=2108454) (change the order to recent/old to check the interval), collected on the previous site before it was suspended, being, apparently, the only public place where these diaries are.


## SUGGESTED ACTION: Make a LAI request to escalate the issue
- Whoever is going to perform the task, signal here so that other people do not do activities already being performed
- It is important to follow the response deadlines and update here with the follow-up
- You can use the space in this thread to talk about the issue (take an action other than the one initially suggested in the opening, develop an initial draft, make an appeal, next steps, who to call, etc).

**Comment by jedibruno** [comment]
Dúvida: seria possível automatizar um registro dessas URLs que raspamos no Internet Archive?

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Doubt: would it be possible to automate a record of these URLs that we scrape in the Internet Archive?

**Comment by trevineju** [comment]
Automatizar eu não sei, @jedibruno :( Talvez o @turicas tenha alguma boa ideia sobre o assunto (recentemente, vi sua apresentação da CryptoRave sobre o projeto Graúna (https://grauna.org.br/) que participa. É como um Internet Archive para sites brasileiros selecionados por uma curadoria.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
I don't know about automating, @jedibruno :( Maybe @turicas has some good idea on the subject (I recently saw his CryptoRave presentation on the Graúna project (https://grauna.org.br/) which he participates in. It's like a Internet Archive for Brazilian sites selected by a curatorship.

**Comment by turicas** [comment]
@trevineju não sei se o Graúna conseguiria ajudar nesse caso em específico, dado que os sites arquivados são selecionados pela equipe do Nupef, mas achei legal a ideia de tentar arquivar automaticamente pelo Internet Archive, porém também não descartaria tentar usar a lei para acionar a prefeitura e conseguir o histórico de volta.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
@trevineju I don't know if Graúna would be able to help in this specific case, given that the archived sites are selected by the Nupef team, but I thought the idea of ​​trying to archive automatically through the Internet Archive was cool, but I also wouldn't rule out trying to use the law to trigger the city hall and get the history back.

**Comment by trevineju** [comment]
Peritoró passou a publicar em um novo site: http://www.transparenciadministrativa.com.br/diario/diariov2.xhtml?token=9de645b503b922df799865ffcb07a6ec7b9cb53e

que tem diários de 2017 até hoje.

**Comment by robokbr** [comment]
> Traduzindo para inglês | Translating to english         
----    
Peritoró started publishing on a new website: http://www.transparenciadministrativa.com.br/diario/diariov2.xhtml?token=9de645b503b922df799865ffcb07a6ec7b9cb53e

which has diaries from 2017 to today.
